application: GAE-APP
version: 1
runtime: php
api_version: 1

handlers:

- url: /CloudFrameWorkService(.+)$
  script: adnbppl.php

# Serve images as static resources.
- url: /(.+\.(gif|png|jpg|css|ico|txt|htm|js))$
  static_files: \1
  upload: .+\.(gif|png|jpg|css|ico|txt|htm|js)$
  application_readable: true
  
- url: /$
  script: adnbppl.php

- url: /CloudFrameWork(.+)$
  script: adnbppl.php
  
- url: /(.+\.(php|html))$
  script: \1
  
# Serve images as static resources.
- url: /(.+\..+)$
  static_files: \1
  upload: .+\..+$
  application_readable: true
  
# Serve php scripts.
- url: /(.+)$
  script: adnbppl.php
  
